name: novus_track
description: A futuristic multipeer car radar over Wi-Fi hotspot.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.8
  firebase_auth: ^4.15.0
  device_info_plus: ^9.0.3
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  flutter_compass: ^0.8.0
  flutter_map_location_marker: ^10.1.0
  sensors_plus: ^3.0.4
  restart_app: ^1.3.2
  google_fonts: ^6.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/car_top.png
    - assets/beep.mp3
